[package]
name = "guac-cli"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
description = "A command-line interface for working with [Guac](https://guac.sh)."

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
guac = { path = "../lib" }
anyhow = "1.0.39"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
serde = "1.0.114"
serde_derive = "1.0.114"
serde_json = "1.0.56"
colored_json = "3.0.1"
clap = { version = "4.0.29", features = ["derive"] }
nats = "0.24.0"
exporter = { git = "https://github.com/trustification/trustification.git", tag="v0.1.0-nightly.9382a428"}
env_logger = "0.10"
log = "0.4.14"
humantime = "2.1.0"
humantime-serde = "1.1.1"
packageurl = "0.3.0"

[[bin]]
name = "guac"
path = "src/main.rs"
