name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install protobuf
      run: |
        sudo apt-get update
        sudo apt-get install protobuf-compiler
    - name: Build
      run: cargo build
    - name: Run guac
      run: docker compose -f example/compose/compose-guac.yaml up --detach --wait --wait-timeout 30
    - name: Run tests
      run: GUAC_URL=http://localhost:8085/query cargo test
